apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
    version: v0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      version: v0
  template:
    metadata:
      labels:
        app: backend
        version: v0
    spec:
      containers:
      - name: backend
        image: fsedano/python-backend:21
        ports:
        - containerPort: 5000
    