apiVersion: v1
kind: Service
metadata:
  name: fe1
spec:
  selector:
    app: fe1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
  loadBalancerIP: 192.168.20.142
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe1
  labels:
    app: fe1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fe1
  template:
    metadata:
      labels:
        app: fe1
    spec:
      containers:
      - name: fe1
        image: fsedano/python-srv1:11
        ports:
        - containerPort: 5000
    