apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
  - "*"
  gateways:
  - httpbin-gateway
  http:
  - route:
    - destination:
        host: fe1
        subset: v1
      headers:
        request:
          set:
            x-user-fran: "v1"
      weight: 30
    - destination:
        host: fe1
        subset: v0
      weight: 30
    - destination:
        host: fe1
        subset: v2
      weight: 40
